//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Train_Details
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_status
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking_status()
        {
            this.Cancelled_ticket = new HashSet<Cancelled_ticket>();
        }
    
        public int Bid { get; set; }
        public Nullable<int> Tno { get; set; }
        public string @class { get; set; }
        public Nullable<System.DateTime> date_of_travel { get; set; }
        public Nullable<int> no_of_ticket { get; set; }
        public Nullable<int> Total_amount { get; set; }
    
        public virtual Train_details Train_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cancelled_ticket> Cancelled_ticket { get; set; }
    }
}
