//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Train_Details
{
    using System;
    using System.Collections.Generic;
    
    public partial class Train_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Train_details()
        {
            this.Booking_status = new HashSet<Booking_status>();
            this.Cancelled_ticket = new HashSet<Cancelled_ticket>();
        }
    
        public int Tno { get; set; }
        public string Tclass { get; set; }
        public string Tname { get; set; }
        public string TSource { get; set; }
        public string TDestination { get; set; }
        public Nullable<int> TotalSeat { get; set; }
        public Nullable<int> AvlSeat { get; set; }
        public string Tstatus { get; set; }
        public Nullable<int> Fare { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking_status> Booking_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cancelled_ticket> Cancelled_ticket { get; set; }
    }
}
