//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Train_Details
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_LogIn
    {
        public decimal User_id { get; set; }
        public string User_Name { get; set; }
        public Nullable<decimal> User_Age { get; set; }
        public string User_Password { get; set; }
    }
}
